# This is a basic workflow to help you get started with Actions
name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [master]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      - run: nix-shell --run 'make build'
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: transparent-top-bar
          path: build/transparent-top-bar@com.ftpix.zip